# Generated by Django 6.0.2 on 2026-02-19 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(max_length=50, unique=True, verbose_name='N° Dossier')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=200, verbose_name='Lieu de naissance')),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10)),
                ('situation', models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)')], default='', max_length=20)),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('profession', models.CharField(blank=True, choices=[('Étudiant', 'Étudiant'), ('Employé', 'Employé'), ('Sans emploi', 'Sans emploi'), ('Autre', 'Autre')], default='', max_length=30)),
                ('type_consultation', models.CharField(blank=True, choices=[('CBV', 'CBV - Coups et Blessures Volontaires'), ('ADC', 'ADC - Accident de la Circulation'), ('AVP', 'AVP - Accident sur Voie Publique')], max_length=5, null=True, verbose_name='Type de consultation')),
                ('itt_jours', models.IntegerField(default=0, verbose_name='ITT (jours)')),
                ('auteur_agression', models.CharField(blank=True, choices=[('Voisin', 'Voisin'), ('Cousin', 'Cousin'), ('Conjoint', 'Conjoint'), ('Parent', 'Parent'), ('Frère/Sœur', 'Frère/Sœur'), ('Inconnu', 'Inconnu'), ('Autre', 'Autre')], default='', max_length=20, verbose_name="Auteur de l'agression")),
                ('autorite_requerante', models.CharField(blank=True, choices=[('Police', 'Police'), ('Gendarmerie', 'Gendarmerie')], default='', max_length=15, verbose_name='Autorité requérante')),
                ('unite', models.CharField(blank=True, choices=[('Thanatologie', 'Thanatologie'), ('Dommage Corporel', 'Dommage Corporel')], default='', max_length=50, verbose_name='Unité')),
                ('sous_unite', models.CharField(blank=True, default='', max_length=50, verbose_name='Sous-unité')),
                ('rapport_medical', models.TextField(blank=True, default='', verbose_name='Rapport médical')),
                ('status', models.CharField(blank=True, default='', max_length=30, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('medecin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_traites', to=settings.AUTH_USER_MODEL, verbose_name='Médecin traitant')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('assign', 'Affectation'), ('delete', 'Suppression')], max_length=10)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='patients.patient')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-timestamp'],
            },
        ),
    ]
